compatibility_date = "2026-04-17"
main = "build/worker/shim.mjs"
name = "nicorandompicker"

[build]
command = "worker-build --release"

[assets]
binding = "ASSETS"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]
